name: Compile changelogs

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  CompileCL:
    runs-on: ubuntu-latest
    if: github.repository == 'vlggms/tegustation-bay12' # to prevent this running on forks
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0 # Otherwise, we will fail to push refs
          ref: dev
          token: ${{ secrets.BOT_TOKEN }}
      - name: Python setup
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: '3.x'
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml bs4
      - name: Compile CL
        run: |
          python tools/changelog/ss13_genchangelog.py html/changelog.html html/changelogs
      - name: Commit And Push
        run: |
          git config --global user.email "${{ secrets.BOT_EMAIL }}"
          git config --global user.name "${{ secrets.BOT_NAME }}"
          git diff --quiet --exit-code && echo "No changes found, abort." && exit 0
          git commit -m "Automatic changelog generation" -a
          git push
